upstream django_server {
    server web:8000;
}

server {
    listen 80;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        proxy_pass http://web:8085;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Đội mũ HTTPS cho tín hiệu
        # Đưa thẻ bài chống lỗi CSRF cho Django
        proxy_set_header Origin $http_origin;
        proxy_set_header Referer $http_referer;

        proxy_redirect off;
    }
}
