version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wms_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wms_db
      MYSQL_USER: wms_user
      MYSQL_PASSWORD: wms_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 10

  wms-app:
    build: .
    container_name: wms-app
    restart: unless-stopped
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn WMS.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: wms_nginx
    restart: unless-stopped
    ports:
      - "8085:80" # <--- PORT NGINX ĐÃ ĐƯỢC ĐỔI THÀNH 8085
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - wms-app

volumes:
  mysql_data:
  static_volume:
  media_volume:
