# Generated by Django 6.0.5 on 2026-05-13 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã Đồng Phục')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Loại Đồng Phục')),
                ('size', models.CharField(max_length=10, verbose_name='Kích cỡ (Size)')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số phiếu')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Ngày thực hiện')),
                ('actor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người giao/nhận')),
                ('type', models.CharField(choices=[('IN', 'Nhập từ Nhà cung cấp'), ('OUT', 'Cấp phát cho Nhân viên')], max_length=3, verbose_name='Loại giao dịch')),
                ('amount', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.uniform', verbose_name='Đồng phục')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100, verbose_name='Cơ sở')),
                ('request_date', models.DateField(verbose_name='Ngày đề xuất')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='SL')),
                ('student_name', models.CharField(max_length=255, verbose_name='Tên học sinh')),
                ('note', models.CharField(default='Kho nợ', max_length=255, verbose_name='Ghi chú')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã trả')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.uniform', verbose_name='Tên đồng phục')),
            ],
        ),
    ]
