# Generated by Django 6.0.5 on 2026-05-14 08:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Tên nhân viên')),
                ('position', models.CharField(max_length=100, verbose_name='Chức vụ')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày xuất')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Ngày nhập (Trả lại)')),
                ('branch', models.CharField(max_length=100, verbose_name='Cơ sở')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã trả kho')),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.uniform', verbose_name='Tên sản phẩm')),
            ],
        ),
    ]
