"""
Django settings for WMS project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-dxmh(q2&ko698g0!t_7)3^wwou%b@!fxfc#0vj%z*tf#ve(o&4'

ALLOWED_HOSTS = ['*']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Khai báo chặn đứng mọi khả năng bóp méo của Nginx/Cloudflare
CSRF_TRUSTED_ORIGINS = [
    'https://wms.vinhle.site',
    'http://wms.vinhle.site',
]

DEBUG = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',

    # Bổ sung quản lý Site của Django
    'django.contrib.sites',

    # Bổ sung các app của allauth (Đã sửa thụt lề chuẩn)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# --- SỬA LỖI THỤT LỀ CỦA ALLAUTH ĐỂ TRÁNH SẬP WEB ---
SITE_ID = 2

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
# Bỏ qua bước xác nhận trung gian, bấm nút Google là tự động chuyển hướng thẳng sang API Google luôn
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '123456789-example.apps.googleusercontent.com', # Thay bằng Client ID thật của bạn
            'secret': 'GOCSPX-example_secret_key', # Thay bằng Secret thật của bạn
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PREFIX': 'OAuth2',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # Đã bật lại để bảo mật token biểu mẫu
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Middleware bắt buộc bổ sung của allauth để quản lý phiên tài khoản công nghệ
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'WMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # Cần cho allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WMS.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wms_db',
        'USER': 'wms_user',
        'PASSWORD': 'wms_password',
        'HOST': 'db',
        'PORT': '3306',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Ho_Chi_Minh' # Đã chuyển về múi giờ Việt Nam để thống kê lưu chuẩn ngày giờ
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ==============================================================================
# CẤU HÌNH GỬI EMAIL THÔNG BÁO VÀ RESET PASS (GMAIL APPS)
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'vinh81800135@gmail.com'
EMAIL_HOST_PASSWORD = 'oybpmwzsypornllh'
DEFAULT_FROM_EMAIL = 'Hệ thống Quản lý Kho WMS <vinh81800135@gmail.com>'
PASSWORD_RESET_TIMEOUT = 86400